### ISSUE TITLE
Problem decoding cf datetime for year 2680, calendar 360-day

### ISSUE THREAD

**Issue by knaughten** [MITgcm/xmitgcm#174]
Hello,

I am running MITgcm with atmospheric forcing from the end of a CMIP6 spinup. The calendar starts in the year 2680 and there are 360 days per month. 

xmitgcm seems to be having trouble with this calendar. When I call open_mdsdataset (with ref_date='2680-01-01 00:00:00' and calendar='360_day') I get the following warning:

`SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netcdftime.datetime objects instead, reason: dates out of range`

which is pointing to the last line in this block of code:

https://github.com/MITgcm/xmitgcm/blob/0b31402fcfb2df1781c64365bc0efef734a7905b/xmitgcm/mds_store.py#L238-L251

When I try to call to_netcdf, it dies with the following error:

`ValueError: unable to infer dtype on variable 'time'; xarray cannot serialize arbitrary Python objects`

which seems to be because the time dtype is not set properly.

However, I tried commenting out that entire block of code in mds_store.py, and everything ran without a problem! So I think the problem is not with xarray, but an edge case for xmitgcm. I expect this block of code is needed for other cases, so commenting it out is not a permanent solution...

Let me know what you think, and if you need more info.
Many thanks,
Kaitlin

**Comment by rabernat** [comment]
Thanks a lot for this report! Just a quick follow-up: can you tell us your `xarray.__version__`?

**Comment by rabernat** [comment]
I dug into this. I think the problem is because we are bypassing some of xarray's decoding mechanisms, and consequently we are not setting the `.encoding` attribute properly on `time`.

Example:
```python
import xarray as xr

units = 'seconds since 2680-01-01 00:00:00'
calendar = '360_day'
attrs = {'units': units,'calendar': calendar }

# method 1 - works
da = xr.DataArray([0, 0], dims=['time'], name='foo',
                  coords={'time': (['time'], [0, 1], attrs)})
ds = xr.decode_cf(da.to_dataset())
print(ds.time.encoding)
ds.to_netcdf('test1.nc')

# method 2 - like xmitgcm - doesn't work
ds2 = da.to_dataset()
ds2.time.data = xr.coding.times.decode_cf_datetime(ds2.time.data, units=units, 
                                         calendar=calendar)
ds2
print(ds2.time.encoding)
ds2.to_netcdf('test2.nc') # raises error
```

Should be an easy fix.

**Comment by knaughten** [comment]
Hi Ryan, my xarray version is 0.10.3. I know this is old but I'm unable to easily update it on my current HPC architecture - long story! So if we can find a solution that works with this version, that would be ideal.

In terms of a fix, I'm not so familiar with the details of xarray, so I don't quite understand what you are suggesting we change in the code. But I'm happy to test out anything you'd like me to.

**Comment by rabernat** [comment]
@knaughten - I fixed your issue in #177. If you install the latest xmitgcm from github, it should work now.

We will do a new release soon.

> my xarray version is 0.10.3. I know this is old but I'm unable to easily update it on my current HPC architecture - long story!

Xarray is now on 0.14.1! If you're able to install xmitgcm, you should be able to install your own version of xarray. On HPC systems, you can usually do `pip install --user ...`. You can also create your own custom conda environment in user space.

**Comment by knaughten** [comment]
Hi Ryan,

Thanks for taking a look at this. I am unfortunately still having some problems - more below - but this might be because updating xarray is continuing to be an absolute headache. pip install --user does not work on this HPC system, so I initially installed xarray using easy_install but this only has the old versions of it. I should be able to update to 0.11.3 at least using conda, but conda is not seeing the xarray installation at all. Happy days! The HPC helpdesk is on the case...

When I call open_mdsdataset I am getting the following warning:

```
/home/n02/n02/kaight/.local/lib/python2.7/site-packages/xarray-0.10.3-py2.7.egg/xarray/coding/times.py:111: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netcdftime.datetime objects instead, reason: dates out of range
  result = decode_cf_datetime(example_value, units, calendar)
/home/n02/n02/kaight/.local/lib/python2.7/site-packages/xarray-0.10.3-py2.7.egg/xarray/coding/variables.py:66: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using dummy netcdftime.datetime objects instead, reason: dates out of range
  return self.func(self.array[key])
{'units': 'seconds since 2680-01-01 00:00:00', 'dtype': dtype('int64'), 'calendar': '360_day'}
{'units': 'seconds since 2680-01-01 00:00:00', 'dtype': dtype('int64'), 'calendar': '360_day'}
{'units': 'seconds since 2680-01-01 00:00:00', 'dtype': dtype('int64'), 'calendar': '360_day'}
```
and then calling ds.to_netcdf dies with the following error:
```
ValueError: unable to infer dtype on variable 'time'; xarray cannot serialize arbitrary Python objects
```

Again, it is probably an xarray version incompatibility. But if I comment out the following lines in mds_store.py, everything works fine:

https://github.com/MITgcm/xmitgcm/blob/de396c2e23795ad8e0367b6f72214909a70ebc6c/xmitgcm/mds_store.py#L257-L259

Why do we need to decode the time at all? Does this introduce some extra functionality that I'm not making use of?

Thanks again for your help.
Cheers,
Kaitlin

**Comment by rabernat** [comment]
> Why do we need to decode the time at all? Does this introduce some extra functionality that I'm not making use of?

Decoding time allows you to make use of all of xarray's [timeseries functionality](http://xarray.pydata.org/en/stable/time-series.html), such as grouping and resampling your data by day, month, year, etc. In general, it's a great thing to have.

However, it should be optional in xmitgcm. You should be able to turn it of by just not specifying a `ref_date` in `open_mdsdataset`. Can you try that?

**Comment by knaughten** [comment]
Turning off ref_date and calendar doesn't cause any problems, but now the time axis doesn't have any units in my NetCDF file, which I still want. It seems that functionality needs ref_date and calendar but decoding is optional.

Regardless, I have FINALLY managed to update my xarray to 0.11.3! So now the problem is gone. I am unfortunately having another problem with the latest version of xmitgcm but I will open another issue for that.

Many thanks for your help.
